### ISSUE TITLE
Allow cloud add with specified IP

### ISSUE THREAD

**Issue by ocgltd** [DoctorMcKay/HSPI_IRobot#8]
I am trying to use the Cloud Add function to add my roomba.  However, the roomba is on a different subnet (so this feature just keeps "SEARCHING").

I know the IP of the roomba, and I (think that I) have opened up the necessary ports to make the roomba accessible.  Can I suggest a feature where the CLOUD ADD function allow me to either search for the roomba, or allow me to specify the IP of the roomba?

I'm jumping through lots of hoops to get the BLID+Password...(messing with dorita too).  This would be very handy

**Comment by DoctorMcKay** [comment]
When cloud auth succeeds, it prints the BLID and password for every robot on your account to the HS4 log. You can get the details from there then manually add the robot by IP.
